name: Build APK from ZIP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Rozpakuj ZIP i nie nadpisuj .github
      - name: Find & unzip project (skip .github)
        shell: bash
        run: |
          set -e
          ZIP_FILE=$(ls -1 *.zip | head -n1 || true)
          if [ -z "$ZIP_FILE" ]; then
            echo "❌ Brak pliku .zip w repo."
            exit 1
          fi
          echo "➡️ ZIP: $ZIP_FILE"
          mkdir extracted
          unzip -o "$ZIP_FILE" -d extracted
          ROOT_DIR=$(ls -1 extracted | head -n1)
          rm -rf "extracted/$ROOT_DIR/.github" || true
          shopt -s dotglob
          mv "extracted/$ROOT_DIR"/* .
          rm -rf extracted
          echo "✅ Rozpakowano."

      # 2) settings.gradle.kts z repozytoriami Google + Maven Central
      - name: Patch settings.gradle.kts
        shell: bash
        run: |
          cat > settings.gradle.kts <<'EOF'
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "FloorFit"
          include(":app")
          EOF
          echo "✅ Nadpisano settings.gradle.kts"

      # 3) app/build.gradle.kts zgodny z Jetpack Compose + Material3
      - name: Patch app/build.gradle.kts for Compose
        shell: bash
        run: |
          mkdir -p app
          cat > app/build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
          }

          android {
              namespace = "pl.floorfit.app"
              compileSdk = 34

              defaultConfig {
                  applicationId = "pl.floorfit.app"
                  minSdk = 24
                  targetSdk = 34
                  versionCode = 1
                  versionName = "1.0"
              }

              buildTypes {
                  release {
                      isMinifyEnabled = false
                      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
                  }
              }

              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }
              kotlinOptions { jvmTarget = "17" }

              buildFeatures { compose = true }
              composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }
              packaging { resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" } }
          }

          dependencies {
              val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
              implementation(composeBom)
              implementation("androidx.activity:activity-compose:1.9.2")
              implementation("androidx.compose.ui:ui")
              implementation("androidx.compose.ui:ui-tooling-preview")
              implementation("androidx.compose.material3:material3:1.2.1")
              implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
              implementation("com.google.android.material:material:1.12.0") // Theme.Material3 w XML
              debugImplementation("androidx.compose.ui:ui-tooling")
          }
          EOF
          echo "✅ Ustawiono build.gradle.kts (Compose)"

      # 4) Minimalny, poprawny manifest (Theme.Material3 działa dzięki material:1.12.0)
      - name: Patch AndroidManifest.xml
        shell: bash
        run: |
          mkdir -p app/src/main
          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="pl.floorfit.app">
              <application
                  android:allowBackup="true"
                  android:label="@string/app_name"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.Material3.Light.NoActionBar">
                  <activity
                      android:name="pl.floorfit.app.MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          echo "✅ Podmieniono AndroidManifest.xml"

      # 5) JDK + Gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          # cache: false  # można odkomentować, by całkiem wyłączyć cache

      # 6) Build APK – pokaż pełny log
      - name: Build debug APK
        run: gradle :app:assembleDebug --stacktrace --info --no-daemon

      # 7) Artefakt do pobrania
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FloorFit-debug-apk
          path: app/build/outputs/apk/debug/*.apk
