name: Build APK from ZIP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Znajdź ZIP i rozpakuj (nie nadpisuj .github)
      - name: Find & unzip project (skip .github)
        shell: bash
        run: |
          set -e
          ZIP_FILE=$(ls -1 *.zip | head -n1 || true)
          if [ -z "$ZIP_FILE" ]; then
            echo "❌ Brak pliku .zip w repo."
            exit 1
          fi
          echo "➡️ ZIP: $ZIP_FILE"
          mkdir extracted
          unzip -o "$ZIP_FILE" -d extracted
          ROOT_DIR=$(ls -1 extracted | head -n1)
          rm -rf "extracted/$ROOT_DIR/.github" || true
          shopt -s dotglob
          mv "extracted/$ROOT_DIR"/* .
          rm -rf extracted
          echo "✅ Rozpakowano."

      # 2) Upewnij się, że repozytoria są ustawione (Google + Maven Central)
      - name: Patch settings.gradle.kts
        shell: bash
        run: |
          cat > settings.gradle.kts <<'EOF'
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "FloorFit"
          include(":app")
          EOF
          echo "✅ Nadpisano settings.gradle.kts"

      # 3) Napraw manifest – wersja minimalna i poprawna
      - name: Patch AndroidManifest.xml
        shell: bash
        run: |
          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="pl.floorfit.app">
              <application
                  android:allowBackup="true"
                  android:label="@string/app_name"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.FloorFit">
                  <activity
                      android:name="pl.floorfit.app.MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          echo "✅ Podmieniono AndroidManifest.xml"

      # 4) JDK + Gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # 5) Build APK
      - name: Build debug APK
        run: gradle :app:assembleDebug

      # 6) Artefakt do pobrania
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FloorFit-debug-apk
          path: app/build/outputs/apk/debug/*.apk
